
language: node_js

script:
- npm run lint
- npm test

before_deploy:
- npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  local-dir: build
  on:
    branch: master